#!/usr/bin/python3
from failover import *
import sys
init(sys.argv[1:])
run_failover()
